"""稳定错误码与异常类型（第 6.9 节）。"""
from __future__ import annotations


# --- 稳定错误码 ---
GPU_REQUIRED = "GPU_REQUIRED"
CUDA_BUILD_MISSING = "CUDA_BUILD_MISSING"
CUDA_DEVICE_INVALID = "CUDA_DEVICE_INVALID"
CUDA_DEVICE_UNAVAILABLE = "CUDA_DEVICE_UNAVAILABLE"
GPU_WORKER_ALREADY_RUNNING = "GPU_WORKER_ALREADY_RUNNING"
GPU_WORKER_LOCK_PERMISSION = "GPU_WORKER_LOCK_PERMISSION"
WORKER_ISOLATION_FAILED = "WORKER_ISOLATION_FAILED"
MODEL_NOT_FOUND = "MODEL_NOT_FOUND"
MODEL_HASH_INVALID = "MODEL_HASH_INVALID"
MODEL_HASH_MISMATCH = "MODEL_HASH_MISMATCH"
MODEL_NOT_POSE = "MODEL_NOT_POSE"
MODEL_DEVICE_MISMATCH = "MODEL_DEVICE_MISMATCH"
MODEL_PRECISION_MISMATCH = "MODEL_PRECISION_MISMATCH"
OUTPUT_DEVICE_MISMATCH = "OUTPUT_DEVICE_MISMATCH"
GPU_POSTPROCESS_DEVICE_MISMATCH = "GPU_POSTPROCESS_DEVICE_MISMATCH"
GPU_MEMORY_LIMIT = "GPU_MEMORY_LIMIT"
GPU_OOM = "GPU_OOM"
CUDA_RUNTIME_ERROR = "CUDA_RUNTIME_ERROR"
WORKER_START_TIMEOUT = "WORKER_START_TIMEOUT"
WORKER_HUNG = "WORKER_HUNG"
WORKER_DIED = "WORKER_DIED"
STALE_WORKER_EPOCH = "STALE_WORKER_EPOCH"
RUNTIME_CONFIG_CONFLICT = "RUNTIME_CONFIG_CONFLICT"
RUNTIME_EVENT_SINK_CONFLICT = "RUNTIME_EVENT_SINK_CONFLICT"
CAPACITY_EVIDENCE_INVALID = "CAPACITY_EVIDENCE_INVALID"
CAPACITY_EXCEEDED = "CAPACITY_EXCEEDED"
CAMERA_SESSION_MISMATCH = "CAMERA_SESSION_MISMATCH"
DUPLICATE_FRAME = "DUPLICATE_FRAME"
STALE_FRAME = "STALE_FRAME"
FRAME_TOO_LARGE = "FRAME_TOO_LARGE"
TORN_FRAME = "TORN_FRAME"
EVENT_QUEUE_OVERFLOW = "EVENT_QUEUE_OVERFLOW"
EVENT_SPOOL_FULL = "EVENT_SPOOL_FULL"
WORKER_JOURNAL_UNAVAILABLE = "WORKER_JOURNAL_UNAVAILABLE"
WORKER_JOURNAL_CORRUPT = "WORKER_JOURNAL_CORRUPT"
PARENT_SPOOL_CORRUPT = "PARENT_SPOOL_CORRUPT"
TRANSITION_ACK_MISMATCH = "TRANSITION_ACK_MISMATCH"


class AiMonitorPoseError(Exception):
    """插件基类异常。"""

    code = "POSE_ERROR"


class ConfigError(ValueError):
    """配置验证错误。为便于测试/调用方捕获，派生自 ValueError。"""
    code = "CONFIG_ERROR"


class ProtocolError(AiMonitorPoseError):
    code = "PROTOCOL_ERROR"


class CudaError(AiMonitorPoseError):
    code = "CUDA_ERROR"


class ModelError(AiMonitorPoseError):
    code = "MODEL_ERROR"


class WorkerError(AiMonitorPoseError):
    code = "WORKER_ERROR"


class TaskBindingError(AiMonitorPoseError):
    code = "TASK_CAMERA_BINDING_ERROR"


class CudaBuildMissingError(Exception):
    code = CUDA_BUILD_MISSING


class CudaUnavailableError(Exception):
    code = CUDA_DEVICE_UNAVAILABLE


class CudaDeviceInvalidError(Exception):
    code = CUDA_DEVICE_INVALID
